### ISSUE TITLE
Adding Linux support

### ISSUE THREAD

**Issue by Flix01** [rasmusbarr/nudge#1]
Hi @rasmusbarr ! 
Wonderful project! Coding a mini physic engine in a single .cpp file must be a tough challenge!

However, I posted this just to say that I've compiled it for Linux (I'm using Ubuntu 16.04 LTS 64bits), with the following changes to main.cpp:
```c++
#ifdef __APPLE__
#include <GLUT/GLUT.h>
#include <OpenGL/gl.h>
#elif _MSC_VER
#include <GLUT/glut.h>
#include <gl/gl.h>
#else // linux
#include <GL/glut.h>
#include <GL/gl.h>
#endif
// Not sure about mingw (if it's like linux or like _MSC_VER)
```
I just used this command line from the example folder::
```
g++ --std=c++11 main.cpp -o main -I"./" -I"../" ../nudge.cpp -lglut -lGL
# Or:
# clang++ --std=c++11 main.cpp -o main -I"./" -I"../" ../nudge.cpp -lglut -lGL
#  optionally use --march=haswell (Using 8-wide AVX FMA: Enabled)
```

Without  --std=c++11, g++ produces a lot of errors.
Strangely, using clang It compiles with only the following warnings:
```
../nudge.cpp:2928:41: warning: default template arguments for a function
      template are a C++11 extension [-Wc++11-extensions]
template<unsigned data_stride, unsigned index_stride = 1, class T>
                                        ^              ~
../nudge.cpp:2973:41: warning: default template arguments for a function
      template are a C++11 extension [-Wc++11-extensions]
template<unsigned data_stride, unsigned index_stride = 1, class T>
                                        ^              ~
../nudge.cpp:3030:41: warning: default template arguments for a function
      template are a C++11 extension [-Wc++11-extensions]
template<unsigned data_stride, unsigned index_stride = 1, class T>
```

However these are just details. Thank you for this project!

**Comment by rasmusbarr** [comment]
Thanks! I'll look into having it compile without --std=c++11. That was my intention initially but I actually never tested it. I'll look into adding a Linux Makefile for the sample application as well.

**Comment by Flix01** [comment]
Ok. 

**[OT]** I'm trying to port the example to emscripten as well (to a .html file), but it's a bit more complex.
Basically I have problems with SSE, because not all the functions inside the SSE headers are present in emscripten and these two lines are not defined:
_MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
_MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);

<mm_malloc.h> was not present too, but as a workaround I could use (in main.cpp after the inclusion of the GL headers):
```cpp
#ifdef __EMSCRIPTEN__
static inline void *
_mm_malloc (size_t size, size_t alignment)
{
  void *ptr;
  if (alignment == 1)
    return malloc (size);
  if (alignment == 2 || (sizeof (void *) == 8 && alignment == 4))
    alignment = sizeof (void *);
  if (posix_memalign (&ptr, alignment, size) == 0)
    return ptr;
  else
    return NULL;
}

static inline void
_mm_free (void * ptr)
{
  free (ptr);
}
#endif //__EMSCRIPTEN__
```
The command-line I used was:
```
em++ -O2 --std=c++11 -msse2 -o html/nudge.html mainLinux.cpp ../nudge.cpp -I"./" -I"../" -s LEGACY_GL_EMULATION=0 --closure 1
```
where mainLinux.cpp is just main.cpp with all the modifications in this thread.

```
mainLinux.cpp:381:26: error: use of undeclared identifier '_MM_FLUSH_ZERO_ON'
        _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
                                ^
mainLinux.cpp:382:30: error: use of undeclared identifier
      '_MM_DENORMALS_ZERO_ON'
        _MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
                                    ^
2 errors generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

Better close this now (emscripten compilation is not a priority for me now).

**Comment by rasmusbarr** [comment]
That's pretty cool. I haven't looked at emscripten personally.

You can actually just remove those two lines (_MM_SET_FLUSH_ZERO_MODE/_MM_SET_DENORMALS_ZERO_MODE). They are not needed for correctness. It's just a performance thing.

If you want to simplify the _mm_malloc replacement, always calling posix_memalign should be alright.

**Comment by Flix01** [comment]
Yes, in the end I've managed to compile it in emscripten.... but it was an (almost useless) exercise.
Main problems were:
* _glutSolidSphere_ and _glutSolidCube_ are not supported and need to be replaced. I used my [teapot.h](https://github.com/Flix01/3D-Signed-Distance-Shapes-Demo/blob/master/teapot.h) for this.
* The allocated memory was too much (and it was not clear how to set enough "arena" space based on the number of bodies. I had to add definitions for every memory quantity (like arena size, arena alignment, max num bodies, num spheres, num cubes,...) and then try to pass "values that worked" in the compilation command line.

There were other tough things to understand about emscripten (at least em++ version 1.37.13), but they were a bit easier to set up:
* glTranslate(...), glPushMatrix(...) and so on work with : -s LEGACY_GL_EMULATION=1
* I had to put at the top of nudge.cpp this snippet (and add to the compiler command line what is written there):
```cpp
#ifdef __EMSCRIPTEN__
// with  -mssse3
// this include statement:
#include <smmintrin.h>
// OR with just -msse2, these 2 lines:
//#define _mm_max_epi32 _mm_max_epi16
//#define _mm_min_epi32 _mm_min_epi16
#endif
```

The result however was the worst performance I have ever seen (nearly 1 frame per second in Firefox or so...). 

And I couldn't even compile to web assembler (with -s WASM=1) to improve performance, because I had this error:
```
Traceback (most recent call last):
  File "/.../emsdk/emscripten/1.37.13/em++", line 16, in <module>
    emcc.run()
  File "/.../emsdk/emscripten/1.37.13/emcc.py", line 1795, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/.../emsdk/emscripten/1.37.13/emcc.py", line 2260, in do_binaryen
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'/.../emsdk/clang/e1.37.13_64bit/binaryen/bin/asm2wasm', 'html/nudge.temp.asm.js', '--total-memory=16777216', '--emit-potential-traps', '-O2', '--mem-init=html/nudge.html.mem', '--mem-base=1024', '--wasm-only', '-o', 'html/nudge.wasm']' returned non-zero exit status -6
```

But at least it worked  :smile:!
![selection_052](https://user-images.githubusercontent.com/9608982/27302521-a823d75a-5537-11e7-8a73-26ea047973bd.png)

**Comment by rasmusbarr** [comment]
Very cool that you got something running :)

Unfortunately I can't help much with emscripten or explain the performance problem. I'm not sure how fast it is supposed to be at SSE code. I can say that the arena used in the sample application is a bit excessive so it should be fine just reducing it. It mostly boils down two how many contacts you can get in a frame.

When setting the number of boxes to 16, the number of spheres to 8, and max_body_count/max_box_count/max_sphere_count to 32, arena.size = 128*1024 worked fine for me.

The sample application wasn't really made to be built upon. The rendering is terrible but I wrote it like that because it's very compact. In the end, the main point was to illustrate how to use the physics library.

After the lastest commit, g++ should work fine. I also removed _mm_min_epi32/_mm_max_epi32 from the project so they shouldn't cause problems now.

**Comment by Flix01** [comment]
> After the lastest commit, g++ should work fine. I also removed _mm_min_epi32/_mm_max_epi32 from the project so they shouldn't cause problems now.

Thank you! Now nudge.cpp can be kept as it is.

> When setting the number of boxes to 16, the number of spheres to 8, and max_body_count/max_box_count/max_sphere_count to 32, arena.size = 128*1024 worked fine for me.

Yes, I've just tested it now, and it seems to work.

> Unfortunately I can't help much with emscripten or explain the performance problem. I'm not sure how fast it is supposed to be at SSE code.

No matter. The Emscripten build was not a priority for me.

P.S. I've tried removing the timer and using a gluIdleFunc with simulate() called inside render() (at a constant time interval). It seems to work slightly faster in emscripten, but not fast enough...

**Comment by Flix01** [comment]
Hi. I thought it was a good thing to post what I've done so far here, for future reference. (Feel free to do with it whatever you like).

Basically I made an alternative main.cpp, without any fixed function pipeline call, called main_no_fpp.cpp.
* It uses the file _teapot.h_ to draw geometry.
* I've also added a very basic _camera support_.
* I've included a _precompiled nudge.html_ file in the example/html subfolder, (so that people can see how slow sse is in the browsers :unamused: )
* All the relevant info are at the top of the _example/main_no_ffp.cpp_ file.

[nudge_no_ffp.zip](https://github.com/rasmusbarr/nudge/files/1091984/nudge_no_ffp.zip)

P.S. I think the original example file is much better (and compact) to understand how nudge.cpp works. 
But feel free to do whatever you like. I've just posted it here because somebody might find it interesting. Bye!

P.S.2. Added specular colour and removed bad clipping. Updated .zip file (and nudge.html inside it).

**Comment by rasmusbarr** [comment]
Thanks! Too bad it's slow.

It seems like SIMD.js is very very slow when not supported natively: https://github.com/kripken/emscripten/issues/4090

The compatibility table here is not very encouraging either: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SIMD#Browser_compatibility

Seems like only nightly Firefox supports it. Perhaps it will get better in the future :)

**Comment by Flix01** [comment]
> Perhaps it will get better in the future :)

Let's wait and see...

**Comment by Flix01** [comment]
Just to say that I've added all my stuff here: https://github.com/Flix01/nudge/tree/master/example
so that I don't lose it...
