### ISSUE TITLE
Build fails when using GCC 8

### ISSUE THREAD

**Issue by Ristovski** [rasmusbarr/nudge#3]
Compiling with GCC 8 causes a compile error:

> ../../nudge.cpp:454:56: error: cannot convert ‘nudge::simd8_float {aka __vector(8) float}’ to ‘__m256i {aka __vector(4) long long int}’ for argument ‘1’ to ‘__m256i _mm256_permute2x128_si256(__m256i, __m256i, int)’
   return _mm256_permute2x128_si256(x, x, i0 | (i1 << 4));

Using clang/LLVM 5 works just fine.
Not yet sure if this is a bug in gcc or not.

**Comment by rasmusbarr** [comment]
Thanks! Should be fixed in 600de4856a9be253706c6c4852f62bcde2b56d14.
