### ISSUE TITLE
[Question] Assertion `count <= (1 << 13)' failed.

### ISSUE THREAD

**Issue by Flix01** [rasmusbarr/nudge#6]
Hi again.

Today I'm playing a bit with the nudge demo, and I've hit the assertion in the title when I increase the total number of bodies. The comment in nudge.cpp says:
```
// Too many colliders. 2^13 is currently the maximum.
```

The question is: Is it related to the number of bodies or to the number of collisions between bodies?

Basically my settings are:
```c++
#define NUM_BOXES 1024*4
#define NUM_SPHERES 1024*4 //1024*3 works fine
#define MAX_BODY_COUNT (NUM_BOXES+NUM_SPHERES+1) // +1 = ground box
static const unsigned max_body_count = MAX_BODY_COUNT;
static const unsigned max_box_count = NUM_BOXES+1;      // +1 = ground box
static const unsigned max_sphere_count = NUM_SPHERES;
#define ARENA_SIZE (32*MAX_BODY_COUNT*MAX_BODY_COUNT/4)
```

**P.S.** However if I use ```1024*4``` boxes and  ```1024*3``` spheres it works perfectly.
This is a .gif with:
```c++
#   define NUM_SIMULATION_STEPS 1
#   define NUM_SIMULATION_ITERATIONS 5 // These seem to be enough to me...
// I've also doubled all the body masses
```
![nudge](https://user-images.githubusercontent.com/9608982/33518368-2325aca6-d794-11e7-8bb9-9d5014ec548d.gif)
This single .cpp physics library seems really powerful :+1: !

**Comment by rasmusbarr** [comment]
It's the number of colliders (boxes + spheres). The limit is based on how I chose to encode collider ids during broadphase. If you set NUM\_BOXES to 4\*1024 and NUM\_SPHERES to 4\*1024 you'll actually get 8\*1024+1 colliders because of the ground box. 8\*1024+1 > 2^13. Setting NUM_SPHERES to 4\*1024-1 should be fine. Nice gif!

**Comment by Flix01** [comment]
Thanks for the clarification :smiley: .
